/* GENERATED by tools/generate_story_audio.py - do not edit by hand.
 *
 * Story Mode's soundtrack, decoded from Assets/Audio/story_mode.mp3 and
 * resampled to the DirectSound rate.  Android only: the GBA ROM has no Story
 * Mode, so audio_story_data.c is compiled by the Android CMake target alone
 * and never linked into SpaceUnlimited.gba. */
#ifndef AUDIO_STORY_DATA_H
#define AUDIO_STORY_DATA_H

#include "platform.h"

extern const s8 snd_story_pcm[];
extern const u32 snd_story_len;

#endif
