#include "story.h"

/* ── The 70 levels ────────────────────────────────────────────────────────
 * Generated to a strict curve: difficulty rises monotonically, every tenth
 * level is a boss, and the mix rotates clear / hunt / survive so no sector
 * plays like the last one.  Field sizes are capped below the engine's
 * MAX_ASTEROIDS / MAX_DRONES budgets so every level can actually spawn. */
const StoryLevel g_story_levels[STORY_LEVEL_COUNT] = {
    { "FIRST LIGHT",
      "The starter ship clears the dock.",
      "Jack flies. That is all it does.",
      OBJ_CLEAR, 6, 1, 0, 102, 104, 52 },
    { "SCRAP DRIFT",
      "Someone shot a freighter here.",
      "Nobody came back for the pieces.",
      OBJ_CLEAR, 7, 1, 0, 104, 108, 59 },
    { "THIN AIR",
      "Three hunters on your tail already.",
      "Word travels fast out here.",
      OBJ_HUNT, 4, 3, 11, 106, 112, 66 },
    { "CHUBB RUN",
      "This was a Chubb supply lane once.",
      "Now it is only rock.",
      OBJ_CLEAR, 8, 1, 0, 108, 116, 73 },
    { "THE NARROWS",
      "No room to turn. Only to hold.",
      "Ride it out, Jack.",
      OBJ_SURVIVE, 11, 1, 27, 110, 120, 80 },
    { "HOLLOW ROCKS",
      "They are hollow. Something did that.",
      "Do not ask what.",
      OBJ_CLEAR, 10, 1, 0, 112, 124, 87 },
    { "SIGNAL LOST",
      "The belt beacon stopped answering.",
      "Its killers are still parked here.",
      OBJ_HUNT, 7, 4, 15, 114, 128, 94 },
    { "DEBRIS TIDE",
      "The tide comes in every few minutes.",
      "You just have to be elsewhere.",
      OBJ_SURVIVE, 13, 2, 29, 116, 132, 101 },
    { "THE APPROACH",
      "Rustjaw's yard is past this field.",
      "He knows you are coming.",
      OBJ_CLEAR, 16, 3, 0, 118, 136, 138 },
    { "RUSTJAW",
      "The Queen's first dog.",
      "All teeth and no patience.",
      OBJ_BOSS, 0, 0, 0, 120, 140, 500 },
    { "OPEN YARD",
      "Past the jaw. Into the yards.",
      "Rust as far as the scope reaches.",
      OBJ_CLEAR, 13, 2, 0, 122, 144, 122 },
    { "IRON RAIN",
      "The yards shed their hulls up here.",
      "Iron falls like weather.",
      OBJ_CLEAR, 14, 2, 0, 124, 148, 129 },
    { "BENT GIRDERS",
      "Hunters nest in the bent steel.",
      "Flush them out.",
      OBJ_HUNT, 11, 4, 21, 126, 152, 136 },
    { "HUNTER PATROL",
      "A patrol runs this lane hourly.",
      "You are twenty minutes early.",
      OBJ_CLEAR, 16, 3, 0, 128, 156, 143 },
    { "DEAD ENGINES",
      "A thousand engines, all cold.",
      "Yours is the only one lit.",
      OBJ_SURVIVE, 18, 3, 32, 130, 160, 150 },
    { "THE PILE UP",
      "Ships stacked where they dropped.",
      "A graveyard nobody dug.",
      OBJ_CLEAR, 17, 3, 0, 132, 164, 157 },
    { "CUTTING LANE",
      "Salvage cutters, repurposed to kill.",
      "They cut you just the same.",
      OBJ_HUNT, 14, 5, 25, 134, 168, 164 },
    { "RED SHIFT",
      "Everything here is falling away.",
      "Including your margin for error.",
      OBJ_SURVIVE, 20, 3, 34, 136, 172, 171 },
    { "TWIN SIGNALS",
      "Two signals, one contact.",
      "Chubbs says that is never good.",
      OBJ_CLEAR, 23, 4, 0, 138, 176, 208 },
    { "THE TWINS",
      "One ship that decided to be two.",
      "Kill it twice.",
      OBJ_BOSS, 0, 0, 0, 140, 180, 750 },
    { "COLD START",
      "The ice fields swallow heat.",
      "Your hull is already complaining.",
      OBJ_CLEAR, 21, 4, 0, 142, 184, 192 },
    { "GLASS SHARDS",
      "Frozen rock breaks like glass.",
      "And cuts like it.",
      OBJ_CLEAR, 21, 4, 0, 144, 188, 199 },
    { "MIRROR DRIFT",
      "Your own ship on the scope. Twice.",
      "Ice reflects. Probably ice.",
      OBJ_HUNT, 18, 6, 31, 146, 192, 206 },
    { "SLOW BURN",
      "Thrust bleeds away out here.",
      "Everything takes longer to die.",
      OBJ_CLEAR, 23, 4, 0, 148, 196, 213 },
    { "FROST LINE",
      "Cross it and you cannot go back warm.",
      "Chubbs went quiet on the radio.",
      OBJ_SURVIVE, 26, 4, 37, 150, 200, 220 },
    { "WHITE OUT",
      "No horizon. No up. Just white.",
      "Fly by the scope alone.",
      OBJ_CLEAR, 24, 4, 0, 152, 204, 227 },
    { "SPLINTERS",
      "Frostwidow's web sheds splinters.",
      "Each one hunts.",
      OBJ_HUNT, 21, 6, 35, 154, 208, 234 },
    { "THE LONG COLD",
      "The longest stretch of the fields.",
      "Nothing here wants you awake.",
      OBJ_SURVIVE, 28, 5, 39, 156, 212, 241 },
    { "WEB OF ICE",
      "The web is a nest, not a trap.",
      "She is home.",
      OBJ_CLEAR, 30, 6, 0, 158, 216, 278 },
    { "FROSTWIDOW",
      "She keeps her kills frozen.",
      "Hold still and you join them.",
      OBJ_BOSS, 0, 0, 0, 160, 220, 1000 },
    { "SALVAGE RUN",
      "The scrapline eats whole fleets.",
      "It is eating yours next.",
      OBJ_CLEAR, 28, 5, 0, 162, 224, 262 },
    { "MAGNET FIELD",
      "The line pulls everything to centre.",
      "Steer against it or be filed.",
      OBJ_CLEAR, 29, 5, 0, 164, 228, 269 },
    { "BOLT STORM",
      "Loose bolts at combat speed.",
      "Cheap way to lose a canopy.",
      OBJ_HUNT, 25, 6, 41, 166, 232, 276 },
    { "CRUSHER LANE",
      "Automated crushers, still running.",
      "Nobody told them the war ended.",
      OBJ_CLEAR, 30, 5, 0, 168, 236, 283 },
    { "TOWED UNDER",
      "Something is towing you in.",
      "Do not let it finish.",
      OBJ_SURVIVE, 33, 6, 42, 170, 240, 290 },
    { "SCRAP HUNTERS",
      "Hunters built from other hunters.",
      "Welded, not born.",
      OBJ_CLEAR, 31, 6, 0, 172, 244, 297 },
    { "THE CONVEYOR",
      "The whole sector is one belt.",
      "It feeds the Titan.",
      OBJ_HUNT, 28, 6, 45, 174, 248, 304 },
    { "HEAVY METAL",
      "The plates get thicker from here.",
      "So do the things wearing them.",
      OBJ_SURVIVE, 34, 6, 44, 176, 252, 311 },
    { "TITAN SHADOW",
      "You are flying in its shadow.",
      "It has not looked down yet.",
      OBJ_CLEAR, 34, 6, 0, 178, 256, 348 },
    { "SCRAP TITAN",
      "It is made of everyone before you.",
      "Do not add to it.",
      OBJ_BOSS, 0, 0, 0, 180, 260, 1250 },
    { "FIRST BURN",
      "Ember Reach. The air itself burns.",
      "Chubbs says keep moving.",
      OBJ_CLEAR, 34, 6, 0, 182, 264, 332 },
    { "SOLAR WIND",
      "The wind here strips paint.",
      "Then plate. Then pilot.",
      OBJ_CLEAR, 34, 6, 0, 184, 268, 339 },
    { "ASH CLOUD",
      "You cannot see them coming.",
      "They can see you fine.",
      OBJ_HUNT, 30, 6, 51, 186, 272, 346 },
    { "FLARE UP",
      "Flares every ninety seconds.",
      "Count them if you like.",
      OBJ_CLEAR, 34, 6, 0, 188, 276, 353 },
    { "THE FURNACE",
      "Nothing survives standing still.",
      "So do not.",
      OBJ_SURVIVE, 34, 6, 47, 190, 280, 360 },
    { "CINDER RUN",
      "Burnt-out hulls, still glowing.",
      "Some of them still shoot.",
      OBJ_CLEAR, 34, 6, 0, 190, 284, 367 },
    { "HEAT DEATH",
      "Your coolant is a suggestion now.",
      "Kill fast, fly faster.",
      OBJ_HUNT, 30, 6, 55, 190, 288, 374 },
    { "MELTLINE",
      "The rock runs like water here.",
      "Hold the line anyway.",
      OBJ_SURVIVE, 34, 6, 49, 190, 292, 381 },
    { "EMBER GATE",
      "The last gate before the whips.",
      "Chubbs stopped joking.",
      OBJ_CLEAR, 34, 6, 0, 190, 296, 418 },
    { "EMBERLASH",
      "Rotating flame. No gaps.",
      "Except one. Find it.",
      OBJ_BOSS, 0, 0, 0, 190, 300, 1500 },
    { "VAULT DOOR",
      "The Cold Vault. It has no windows.",
      "Nothing built it. It was always here.",
      OBJ_CLEAR, 34, 6, 0, 190, 304, 402 },
    { "DARK CORRIDOR",
      "No stars. No light. No sound.",
      "Only your own engine.",
      OBJ_CLEAR, 34, 6, 0, 190, 308, 409 },
    { "SILENT ALARM",
      "You tripped something a mile back.",
      "Nothing came. That is worse.",
      OBJ_HUNT, 30, 6, 61, 190, 312, 416 },
    { "LOCKDOWN",
      "The Vault sealed behind you.",
      "Forward is the only door.",
      OBJ_CLEAR, 34, 6, 0, 190, 316, 423 },
    { "THE STACKS",
      "Rows of ships in storage.",
      "Every one of them a Chubb's.",
      OBJ_SURVIVE, 34, 6, 52, 190, 320, 430 },
    { "GHOST FLEET",
      "The fleet that tried before you.",
      "All of it. Still docked.",
      OBJ_CLEAR, 34, 6, 0, 190, 324, 437 },
    { "DEEP STORAGE",
      "She keeps what she takes.",
      "Jack sees his old planet's colours.",
      OBJ_HUNT, 30, 6, 65, 190, 328, 444 },
    { "NO LIGHT",
      "The Warden dims the whole sector.",
      "Fly on instinct.",
      OBJ_SURVIVE, 34, 6, 54, 190, 332, 451 },
    { "WARDEN WAKES",
      "Four nodes just lit up.",
      "It knows your name.",
      OBJ_CLEAR, 34, 6, 0, 190, 336, 488 },
    { "VAULT WARDEN",
      "It does not attack. It denies.",
      "Take the door from it.",
      OBJ_BOSS, 0, 0, 0, 190, 340, 1750 },
    { "THIN REALITY",
      "Space stops behaving here.",
      "The Queen's own front garden.",
      OBJ_CLEAR, 34, 6, 0, 190, 344, 472 },
    { "FOLDED SPACE",
      "You pass the same rock twice.",
      "Because you did.",
      OBJ_CLEAR, 34, 6, 0, 190, 348, 479 },
    { "ECHO RUN",
      "Every shot you fire comes back.",
      "Aim like it matters.",
      OBJ_HUNT, 30, 6, 71, 190, 352, 486 },
    { "THE UNMAKING",
      "Things here are being deleted.",
      "Slowly. Out of order.",
      OBJ_CLEAR, 34, 6, 0, 190, 356, 493 },
    { "QUEENS GUARD",
      "Her guard were Chubbs once.",
      "They do not remember.",
      OBJ_SURVIVE, 34, 6, 57, 190, 360, 500 },
    { "SHATTERED SKY",
      "The sky broke and stayed broken.",
      "Fly through the crack.",
      OBJ_CLEAR, 34, 6, 0, 190, 364, 507 },
    { "NO TOMORROW",
      "She is unmaking the day ahead.",
      "Get there first.",
      OBJ_HUNT, 30, 6, 75, 190, 368, 514 },
    { "THE LAST MILE",
      "One mile. Everything she has left.",
      "Chubbs: come back, Jack.",
      OBJ_SURVIVE, 34, 6, 59, 190, 372, 521 },
    { "GATE OPEN",
      "The Reality Gate stands open.",
      "She left it that way for you.",
      OBJ_CLEAR, 34, 6, 0, 190, 376, 558 },
    { "REALITY QUEEN",
      "Jack RK. The Reality King's own.",
      "Revenge, or nothing.",
      OBJ_BOSS, 0, 0, 0, 190, 380, 2000 },
};

static const char* const s_sector_names[STORY_SECTOR_COUNT] = {
    "THE CHUBB BELT",
    "THE RUST YARDS",
    "THE ICE FIELDS",
    "THE SCRAPLINE",
    "EMBER REACH",
    "THE COLD VAULT",
    "THE REALITY GATE"
};

static const char* const s_boss_names[STORY_SECTOR_COUNT] = {
    "RUSTJAW",
    "THE TWINS",
    "FROSTWIDOW",
    "SCRAP TITAN",
    "EMBERLASH",
    "VAULT WARDEN",
    "THE REALITY QUEEN"
};

/* Nobody's face is ever shown - the Chubbs are only ever voices on the radio,
 * so the bosses only ever get one line of text each. */
static const char* const s_boss_taunts[STORY_SECTOR_COUNT] = {
    "SO THE LITTLE SHIP FLIES",
    "WE ARE TWO. YOU ARE ONE.",
    "HOLD STILL. IT IS WARMER FROZEN.",
    "YOU ARE SCRAP THAT MOVES",
    "BURN LIKE YOUR LAST PLANET DID",
    "THE VAULT DOES NOT OPEN",
    "JACK. MY JACK. COME HOME."
};

const char* story_sector_name(int sector) {
    if (sector < 0 || sector >= STORY_SECTOR_COUNT) return "UNKNOWN SPACE";
    return s_sector_names[sector];
}

const char* story_boss_name(int boss_id) {
    if (boss_id < 0 || boss_id >= STORY_SECTOR_COUNT) return "UNKNOWN";
    return s_boss_names[boss_id];
}

const char* story_boss_taunt(int boss_id) {
    if (boss_id < 0 || boss_id >= STORY_SECTOR_COUNT) return "";
    return s_boss_taunts[boss_id];
}

int story_boss_for_level(int level) {
    if (level <= 0 || level > STORY_LEVEL_COUNT) return -1;
    if ((level % STORY_SECTOR_LEVELS) != 0) return -1;
    return (level / STORY_SECTOR_LEVELS) - 1;
}

/* The opening speech. Kept in the player's own voice - plain, a bit rambling,
 * the way it was told - just given room to breathe across 14 pages. */
const char* const g_story_intro[STORY_INTRO_PAGES][2] = {
    { "Once upon a time,",            "in another universe..." },
    { "Aliens invaded",               "the Chubbs." },
    { "The Chubbs tried to fight",    "back against the Reality King." },
    { "They threw everything",        "they had at him." },
    { "But he was too strong.",       "Way too strong." },
    { "A wise person once said:",     "if you can't beat em, join em." },
    { "So the Chubbs decided",        "to befriend the Reality King." },
    { "Jack RK.",                     "Jack Arkey, they called him." },
    { "He knew a lot about tech",     "from his last planet." },
    { "So he knows how",              "to build a space ship." },
    { "And he wanted revenge.",       "He wanted it badly." },
    { "So he built the ship.",        "The starter ship." },
    { "Nothing special. It flies,",   "it shoots, and it is his." },
    { "And he set aflight,",          "to try and get revenge..." }
};
