#include "story.h"

/* ── The 70 levels ────────────────────────────────────────────────────────
 * Difficulty rises monotonically and every tenth level is a boss, but the
 * shape of a level is deliberately never twice the same.  Two axes do the
 * work:
 *
 *   OBJECTIVE  clear / hunt / survive / big-game / timed - five ways to end
 *              a level, so "kill everything" is only one level in four.
 *   MODIFIER   a twist on the field itself (boulders, shards, swarm, swift,
 *              tough, trickle, storm, snipers) that changes what you are
 *              actually flying through rather than just how much of it.
 *
 * Each sector runs its own hand-picked sequence of the two (see PLANS in the
 * generator note below), chosen so no objective+modifier pair repeats back
 * to back and no sector plays like the one before it.  Field sizes stay
 * inside the engine's MAX_ASTEROIDS / MAX_DRONES budgets so every level can
 * actually spawn, and tools/story_sim proves every one still terminates. */
const StoryLevel g_story_levels[STORY_LEVEL_COUNT] = {
    { "DEEP SPACE",
      "Engines humming in the void.",
      "Testing the flight systems.",
      OBJ_CLEAR, 6, 1, 0, 102, 104, 52, MOD_NONE },
    { "IRON DRIFT",
      "Old debris from the Rim wars.",
      "Clear a path through the junk.",
      OBJ_CLEAR, 6, 1, 0, 104, 108, 65, MOD_TRICKLE },
    { "SCOUT PATROL",
      "Imperial scouts spotted you.",
      "Leave no witnesses behind.",
      OBJ_HUNT, 5, 3, 12, 106, 112, 72, MOD_NONE },
    { "ASTEROID RUN",
      "Heavy rocks in this sector.",
      "Watch for the big ones.",
      OBJ_BIGGAME, 6, 1, 4, 108, 116, 80, MOD_BOULDERS },
    { "THE CROSSING",
      "A narrow gap in the field.",
      "Hold them off as you pass.",
      OBJ_SURVIVE, 15, 2, 28, 110, 120, 95, MOD_SHARDS },
    { "HIDDEN BASE",
      "An old outpost, now abandoned.",
      "Sweep for Imperial tech.",
      OBJ_CLEAR, 12, 2, 0, 112, 124, 105, MOD_SWIFT },
    { "SNIPER ALLEY",
      "Long-range drones are active.",
      "Stay moving or get tagged.",
      OBJ_HUNT, 8, 4, 16, 114, 128, 115, MOD_SNIPERS },
    { "TIMED ESCAPE",
      "The sector is closing down.",
      "Break through before lockdown.",
      OBJ_TIMED, 15, 2, 85, 116, 132, 130, MOD_NONE },
    { "RIM OUTPOST",
      "The last gate to the Nebula.",
      "It is heavily guarded.",
      OBJ_CLEAR, 20, 4, 0, 118, 136, 160, MOD_STORM },
    { "VANGUARD ONE",
      "The Empire's first guardian.",
      "It will not let you pass.",
      OBJ_BOSS, 0, 0, 0, 120, 140, 500, MOD_NONE },
    { "NEBULA ENTRY",
      "The air is thick with iron.",
      "Sensors are struggling.",
      OBJ_CLEAR, 15, 3, 0, 122, 144, 140, MOD_TOUGH },
    { "STEEL RAIN",
      "Falling debris from the yards.",
      "Keep your shields up.",
      OBJ_BIGGAME, 10, 2, 4, 124, 148, 155, MOD_BOULDERS },
    { "SWARM NEST",
      "Hunters are breeding here.",
      "Don't get surrounded.",
      OBJ_SURVIVE, 15, 8, 25, 126, 152, 165, MOD_SWARM },
    { "SHARD BELT",
      "Micro-debris at high speed.",
      "A test of reflexes.",
      OBJ_TIMED, 22, 4, 88, 128, 156, 180, MOD_SHARDS },
    { "DARK ENGINES",
      "Cold ships waiting to strike.",
      "Wake them up.",
      OBJ_HUNT, 20, 4, 35, 130, 160, 200, MOD_NONE },
    { "THE GRAVEYARD",
      "A field of fallen heroes.",
      "Give them their final rest.",
      OBJ_CLEAR, 22, 4, 0, 132, 164, 215, MOD_STORM },
    { "CUTTER SQUAD",
      "Imperial demolition teams.",
      "They slice through hulls.",
      OBJ_BIGGAME, 16, 3, 4, 134, 168, 230, MOD_TOUGH },
    { "VOID PULSE",
      "The void is pulling you in.",
      "Resist the gravity well.",
      OBJ_SURVIVE, 24, 3, 38, 136, 172, 250, MOD_SNIPERS },
    { "DUAL THREAT",
      "Two signals, both hostile.",
      "Divide and conquer.",
      OBJ_CLEAR, 26, 5, 0, 138, 176, 280, MOD_SWIFT },
    { "THE DUALITY",
      "A twin-core warship.",
      "One soul, two bodies.",
      OBJ_BOSS, 0, 0, 0, 140, 180, 750, MOD_NONE },
    { "CRYSTAL DRIFT",
      "Frozen systems, silent stars.",
      "Your hull is icing over.",
      OBJ_CLEAR, 30, 5, 0, 142, 184, 300, MOD_SHARDS },
    { "GLASS STORM",
      "Crystalline shards everywhere.",
      "Fragile but deadly.",
      OBJ_TIMED, 25, 5, 92, 144, 188, 320, MOD_SWIFT },
    { "ECHO FLEET",
      "Ghost signals in the ice.",
      "Hunt the phantoms.",
      OBJ_HUNT, 22, 8, 36, 146, 192, 340, MOD_SWARM },
    { "ABSOLUTE ZERO",
      "Thermal systems failing.",
      "Kill before you freeze.",
      OBJ_SURVIVE, 32, 5, 48, 148, 196, 360, MOD_SHARDS },
    { "GLACIER RUN",
      "Giant icebergs ahead.",
      "Break them down.",
      OBJ_BIGGAME, 30, 3, 4, 150, 200, 380, MOD_NONE },
    { "WHITE OUT",
      "Blinding crystal dust.",
      "Fly by instinct.",
      OBJ_CLEAR, 24, 6, 0, 152, 204, 400, MOD_TRICKLE },
    { "COLD WING",
      "Elite frost fighters.",
      "They hunt in packs.",
      OBJ_HUNT, 25, 8, 40, 154, 208, 420, MOD_SWIFT },
    { "STERN CHASE",
      "A long run through the wastes.",
      "Do not look back.",
      OBJ_SURVIVE, 36, 6, 45, 156, 212, 450, MOD_STORM },
    { "ICICLE POINT",
      "The heart of the waste.",
      "Break the barrier.",
      OBJ_TIMED, 22, 8, 105, 158, 216, 480, MOD_BOULDERS },
    { "FROST STRIKER",
      "A beast of ice and steel.",
      "Warm her heart with fire.",
      OBJ_BOSS, 0, 0, 0, 160, 220, 1000, MOD_NONE },
    { "FORGE GATE",
      "Entering the industrial core.",
      "The air is heavy here.",
      OBJ_BIGGAME, 32, 3, 5, 162, 224, 500, MOD_TOUGH },
    { "PULSE FIELD",
      "Magnetic storms ahead.",
      "Keep your course steady.",
      OBJ_CLEAR, 36, 6, 0, 164, 228, 530, MOD_STORM },
    { "BOLT RUN",
      "Loose rivets at warp speed.",
      "Armor is no protection.",
      OBJ_HUNT, 30, 6, 48, 166, 232, 560, MOD_SNIPERS },
    { "CRUSHER PASS",
      "Automated heavy machinery.",
      "Watch the patterns.",
      OBJ_TIMED, 35, 6, 108, 168, 236, 590, MOD_TOUGH },
    { "CHAIN LINK",
      "The Empire is linking systems.",
      "Break the connection.",
      OBJ_SURVIVE, 36, 8, 48, 170, 240, 620, MOD_SWARM },
    { "SCRAP WING",
      "Rebuilt Imperial fighters.",
      "Twice as dangerous.",
      OBJ_CLEAR, 22, 8, 0, 172, 244, 650, MOD_BOULDERS },
    { "THE LINE",
      "The main supply conveyor.",
      "Cut the line.",
      OBJ_HUNT, 32, 8, 52, 174, 248, 680, MOD_SWIFT },
    { "HEAVY METAL",
      "Reinforced asteroid armor.",
      "Bring the big guns.",
      OBJ_SURVIVE, 38, 8, 50, 176, 252, 710, MOD_TOUGH },
    { "TITAN REACH",
      "In the shadow of the giant.",
      "Don't get noticed.",
      OBJ_BIGGAME, 38, 4, 6, 178, 256, 750, MOD_STORM },
    { "STEEL TITAN",
      "A mountain of moving metal.",
      "Find the weak points.",
      OBJ_BOSS, 0, 0, 0, 180, 260, 1250, MOD_NONE },
    { "SOLAR FLARE",
      "Entering the burning sector.",
      "Keep the heat sinks open.",
      OBJ_CLEAR, 38, 8, 0, 182, 264, 800, MOD_SWIFT },
    { "SUN WIND",
      "Solar radiation levels rising.",
      "Shields are bleeding energy.",
      OBJ_TIMED, 38, 8, 110, 184, 268, 840, MOD_STORM },
    { "ASH WING",
      "Fighters cloaked in fire.",
      "Kill them where they stand.",
      OBJ_HUNT, 34, 8, 58, 186, 272, 880, MOD_SWARM },
    { "MAGMA DRIFT",
      "Liquid rock and white heat.",
      "The stars are screaming.",
      OBJ_BIGGAME, 38, 4, 6, 188, 276, 920, MOD_SWIFT },
    { "THE CRUCIBLE",
      "Only the strong survive here.",
      "A trial of fire.",
      OBJ_SURVIVE, 38, 8, 55, 190, 280, 960, MOD_SHARDS },
    { "CINDER WING",
      "Burnt-out Imperial vets.",
      "They have nothing left to lose.",
      OBJ_CLEAR, 38, 8, 0, 190, 284, 1000, MOD_TOUGH },
    { "NO ESCAPE",
      "The heat is closing in.",
      "Move or melt.",
      OBJ_TIMED, 34, 8, 120, 190, 288, 1050, MOD_SWIFT },
    { "LAVA FALL",
      "Rivers of molten iron.",
      "Watch your step.",
      OBJ_SURVIVE, 38, 8, 60, 190, 292, 1100, MOD_STORM },
    { "GATE KEEPER",
      "The last guard of the sector.",
      "Break their formation.",
      OBJ_HUNT, 38, 7, 65, 190, 296, 1200, MOD_SNIPERS },
    { "INFERNO DRAKE",
      "The fire that never dies.",
      "Extinguish the flame.",
      OBJ_BOSS, 0, 0, 0, 190, 300, 1500, MOD_NONE },
    { "VOID ENTRY",
      "Entering the void core.",
      "Light is an enemy here.",
      OBJ_CLEAR, 32, 8, 0, 190, 304, 1300, MOD_TRICKLE },
    { "SHADOW RUN",
      "Flying in complete darkness.",
      "Trust your instruments.",
      OBJ_BIGGAME, 38, 4, 6, 190, 308, 1350, MOD_TOUGH },
    { "SILENT WING",
      "They don't make a sound.",
      "But they kill just as well.",
      OBJ_HUNT, 34, 7, 70, 190, 312, 1400, MOD_SNIPERS },
    { "DARK PRISON",
      "Trapped in the void's grasp.",
      "Fight your way out.",
      OBJ_SURVIVE, 38, 8, 65, 190, 316, 1450, MOD_SWARM },
    { "STORAGE DEPOT",
      "Where stolen dreams are kept.",
      "Clear the bay.",
      OBJ_TIMED, 25, 8, 125, 190, 320, 1500, MOD_BOULDERS },
    { "GHOST SQUAD",
      "Echoes of the resistance.",
      "Finish what they started.",
      OBJ_CLEAR, 38, 8, 0, 190, 324, 1550, MOD_SHARDS },
    { "CORE RELIC",
      "The heart of a dead system.",
      "Destroy the Imperial core.",
      OBJ_HUNT, 34, 8, 75, 190, 328, 1600, MOD_SWARM },
    { "PITCH BLACK",
      "The light has been stolen.",
      "Become the light.",
      OBJ_SURVIVE, 38, 8, 62, 190, 332, 1650, MOD_TOUGH },
    { "VOID REACH",
      "The Sentinel has woken.",
      "Dodge the beams.",
      OBJ_BIGGAME, 25, 4, 8, 190, 336, 1700, MOD_BOULDERS },
    { "VOID SENTINEL",
      "The eye that never sleeps.",
      "Blot it out.",
      OBJ_BOSS, 0, 0, 0, 190, 340, 1750, MOD_NONE },
    { "RIFT VALLEY",
      "Reality is tearing apart.",
      "Stay in the center.",
      OBJ_TIMED, 38, 8, 130, 190, 344, 1800, MOD_SWIFT },
    { "FOLDED STARS",
      "Space is looping back.",
      "Break the cycle.",
      OBJ_CLEAR, 38, 8, 0, 190, 348, 1850, MOD_STORM },
    { "REFLECTION",
      "Your own shots coming back.",
      "Be precise.",
      OBJ_BIGGAME, 35, 4, 8, 190, 352, 1900, MOD_TOUGH },
    { "UNMAKING",
      "The universe is unraveling.",
      "Keep it together.",
      OBJ_HUNT, 38, 8, 75, 190, 356, 1950, MOD_SWARM },
    { "ROYAL GUARD",
      "The Queen's elite pilots.",
      "Test your metal.",
      OBJ_SURVIVE, 38, 8, 65, 190, 360, 2000, MOD_SHARDS },
    { "BROKEN SKY",
      "Cracks in the firmament.",
      "Fly through the gaps.",
      OBJ_TIMED, 38, 8, 135, 190, 364, 2050, MOD_TOUGH },
    { "FINAL DAWN",
      "The last stand before the end.",
      "For the galaxy.",
      OBJ_CLEAR, 22, 8, 0, 190, 368, 2100, MOD_BOULDERS },
    { "ONE MILE",
      "The Queen's last defense.",
      "Break through.",
      OBJ_HUNT, 38, 7, 70, 190, 372, 2150, MOD_SNIPERS },
    { "REALITY GATE",
      "The gate is open.",
      "Enter the throne room.",
      OBJ_SURVIVE, 38, 8, 75, 190, 376, 2200, MOD_STORM },
    { "SHADOW QUEEN",
      "Kaelen. Your journey ends.",
      "Victory or oblivion.",
      OBJ_BOSS, 0, 0, 0, 190, 380, 2500, MOD_NONE },
};

/* Modifier labels for the level banner and the map card. Kept short so they
 * fit beside the objective on a 240 px line. */
static const char* const s_modifier_names[MOD_COUNT] = {
    "",                 /* MOD_NONE - nothing to announce */
    "BOULDER FIELD",
    "SHARD STORM",
    "HUNTER SWARM",
    "FAST SPACE",
    "ARMOURED ROCK",
    "SLOW DRIP",
    "CONSTANT STORM",
    "SHARPSHOOTERS"
};

const char* story_modifier_name(int mod) {
    if (mod <= MOD_NONE || mod >= MOD_COUNT) return "";
    return s_modifier_names[mod];
}

static const char* const s_sector_names[STORY_SECTOR_COUNT] = {
    "THE OUTER RIM",
    "IRON NEBULA",
    "CRYSTAL WASTES",
    "FORGE WORLDS",
    "BURNING SECTOR",
    "THE VOID CORE",
    "SHADOW HORIZON"
};

static const char* const s_boss_names[STORY_SECTOR_COUNT] = {
    "VANGUARD ONE",
    "THE DUALITY",
    "FROST STRIKER",
    "STEEL TITAN",
    "INFERNO DRAKE",
    "VOID SENTINEL",
    "THE SHADOW QUEEN"
};

/* Nobody's face is ever shown - the radio voices guide you,
 * and the bosses only ever get one line of text each. */
static const char* const s_boss_taunts[STORY_SECTOR_COUNT] = {
    "YOU SHALL NOT PASS THE RIM.",
    "WE ARE TWO. YOU ARE NONE.",
    "STAY STILL. FREEZE FOREVER.",
    "CRUSHED BY SUPERIOR METAL.",
    "BURN IN THE HEART OF RUIN.",
    "THE VOID DOES NOT FORGIVE.",
    "KAELEN. MY PILOT. COME HOME."
};

const char* story_sector_name(int sector) {
    if (sector < 0 || sector >= STORY_SECTOR_COUNT) return "UNKNOWN SPACE";
    return s_sector_names[sector];
}

const char* story_boss_name(int boss_id) {
    if (boss_id < 0 || boss_id >= STORY_SECTOR_COUNT) return "UNKNOWN";
    return s_boss_names[boss_id];
}

const char* story_boss_taunt(int boss_id) {
    if (boss_id < 0 || boss_id >= STORY_SECTOR_COUNT) return "";
    return s_boss_taunts[boss_id];
}

int story_boss_for_level(int level) {
    if (level <= 0 || level > STORY_LEVEL_COUNT) return -1;
    if ((level % STORY_SECTOR_LEVELS) != 0) return -1;
    return (level / STORY_SECTOR_LEVELS) - 1;
}

/* The opening speech. Kept in the player's own voice - plain, a bit rambling,
 * the way it was told - just given room to breathe across 14 pages. */
const char* const g_story_intro[STORY_INTRO_PAGES][2] = {
    { "The Shadow Empire",            "has conquered the stars." },
    { "Systems fell one by one",      "to their cold machines." },
    { "Freedom became a myth,",       "whispered in the dark." },
    { "But in the far reaches,",      "a pilot named Kaelen" },
    { "refused to let hope die.",     "In a hidden hangar," },
    { "they spent years",             "building a defiance." },
    { "Scavenging ancient tech",      "and experimental cores." },
    { "A ship was born from",         "the wreckage of war." },
    { "Swift, deadly, and",           "ready to strike back." },
    { "The path ahead is long",       "and filled with danger." },
    { "The Shadow Queen awaits",      "at the reality's edge." },
    { "But Kaelen has a mission.",    "Revenge for the fallen." },
    { "It is time to ignite",         "the engines of rebellion." },
    { "The galaxy will be free.",     "The hunt begins now." }
};
