#ifndef BOSS_GFX_H
#define BOSS_GFX_H

#include "types.h"

/* Boss hull sprites, authored in the SAME pixel language AND the same
 * nose-up orientation as the player ship templates (hull ramp 33..38,
 * glow 16, canopy D-glass in an s frame, accent mask 241..243 remapped
 * onto a paint ramp at draw time), then flipped vertically at generation
 * time because bosses fly nose-down toward the player.
 * Generated by tools/generate_boss_art.py - edit the art there. */

#define BOSS_SPR_W 24
#define BOSS_SPR_H 20
#define NUM_BOSS_SPRITES 9

typedef enum {
    BOSS_SPR_RAZORWING = 0,    /* arcade mini-boss (waves 5/15/25...) */
    BOSS_SPR_GOLIATH,          /* arcade battleship (waves 10/20/30...) */
    BOSS_SPR_IRONMAW,          /* story L10 */
    BOSS_SPR_GEMINI,           /* story L20 */
    BOSS_SPR_FROSTBITE,        /* story L30 */
    BOSS_SPR_JUGGERNAUT,       /* story L40 */
    BOSS_SPR_INFERNO,          /* story L50 */
    BOSS_SPR_AEGIS,            /* story L60 */
    BOSS_SPR_EMPRESS           /* story L70 */
} BossSpriteId;

extern const u8 spr_boss[NUM_BOSS_SPRITES][BOSS_SPR_W * BOSS_SPR_H];

/* Default paint ramp (accent 0..7) per boss - the same ramps the ship
 * paints use. */
extern const u8 boss_default_accent[NUM_BOSS_SPRITES];

#endif
